sudo: false
language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
os:
  - linux
  - osx
  - windows
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: change

jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm test
    - stage: publish
      node_js: 8
      os: linux
      script:
        - npm test
        - npm run report-coverage
      after_success:
        - npm run semantic-release
